### ISSUE TITLE
Better usage of css-classes

### ISSUE THREAD

**Issue by 720degreeLotus** [ch-a-os/DocSort#116]
Like in `menu.component.scss`:
```css
#home a:hover, #upload a:hover, #search a:hover, #tags a:hover, #history a:hover {
    transition: border 0.2s;
    border-left: 10px solid orangered;
}
```
We should try to give classnames to every important html-element and use those classnames to bind certain scss-rules to the element.
